name: 'Clon'

description: "workflows."

inputs:
  owner:
    description: 'Repository Owner'
    required: true
  repository:
    description: 'Repository name'
    required: true
    default: "BR_kernel_a02"
 branch:
    description: 'Branch name'
    required: true
    default: "kernelku"

runs:
  using: 'composite'
  steps:
    - name: Clone repository
      run: |
        git clone --branch "${{ inputs.branch }}" https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git  --recursive
      shell: bash

branding:
  icon: 'download'
  color: 'blue'

